#baseURL: https=//behdanisohrab.github.io/
languageCode: en-us
title: Sohrab Behdani
theme: "PaperMod"
params:
  defaultTheme: auto
  socialIcons:
    - name: email
      url: mailto:behdanisohrab@gmail.com
    - name: github
      url: https://github.com/behdanisohrab
    - name: twitter
      url: https://twitter.com/behdanisohrab1
    - name: linkedin
      url: https://www.linkedin.com/in/sohrab-behdani-047275254
    - name: stackoverflow
      url: https://stackoverflow.com/users/20324202/sohrab-behdani

  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  profileMode:
    enabled: true
    title: Sohrab`s personal blog.
    subtitle: I will write my ideas and some fun stuff in here :)
menu:
  main:
    - weight: 1
      identifier: about
      name: about
      title: about
      url: /about/
    - weight: 2
      identifier: blog
      name: blog
      title: blog
      url: /blog/
    - weight: 3
      identifier: tags
      name: tags
      title: tags
      url: /tags/
    - weight: 4
      title: search
      url: /search/
taxonomies:
  tag: tags

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

    # analytics:
  # googleAnalytics: 
