#baseURL: https=//behdanisohrab.github.io/
languageCode: en-us
title: Sohrab Behdani
theme: "PaperMod"
params:
  defaultTheme: auto
  socialIcons:
    - name: Instagram
      url: https://instagram.com/sohrabbehdani
    - name: Youtube
      url: https://youtube.com/@sohrabbehdani
    - name: Email
      url: mailto:behdanisohrab@gmail.com
    - name: Github
      url: https://github.com/behdanisohrab
    - name: Twitter
      url: https://twitter.com/behdanisohrab1
    - name: Linkedin
      url: https://www.linkedin.com/in/sohrab-behdani-047275254
    - name: Stackoverflow
      url: https://stackoverflow.com/users/20324202/sohrab-behdani
    - name: Telegram
      url: https://t.me/sbstuff
    - name: Devto
      url: https://dev.to/behdanisohrab
  ShowReadingTime: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  comments: true
  hideSummary: false
  showtoc: true
  tocopen: false
  profileMode:
    enabled: true
    imageUrl: "https://avatars.githubusercontent.com/u/72007820?s=400&u=b4edfbb1458f1f6486de03b2dd503cf48e920604&v=4"
    imageWidth: 120
    imageHeight: 120
    title: Sohrab`s personal blog.
    subtitle: I will write my ideas and some fun stuff in here :)
menu:
  main:
    - weight: 1
      identifier: about
      name: about
      title: About Me
      url: /about/
    - weight: 2
      identifier: blog
      name: blog
      url: /blog/
    - weight: 3
      identifier: tags
      name: tags
      url: /tags/
    - weight: 4
      identifier: search
      name: search
      url: /search/
taxonomies:
  tag: tags

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: monokai

    # analytics:
  # googleAnalytics: 
